#!/command/with-contenv bash
# shellcheck shell=bash

# download patch
wget -qNO /usr/local/bin/patch.sh https://raw.githubusercontent.com/keylase/nvidia-patch/master/patch.sh
chmod "+x" /usr/local/bin/patch.sh

# copied from https://github.com/keylase/nvidia-patch/blob/master/docker-entrypoint.sh
echo "/patched-lib" > /etc/ld.so.conf.d/000-patched-lib.conf
mkdir -p "/patched-lib"
PATCH_OUTPUT_DIR=/patched-lib /usr/local/bin/patch.sh
cd /patched-lib || exit
for f in * ; do
    suffix="${f##*.so}"
    name="$(basename "$f" "$suffix")"
    [ -h "$name" ] || ln -sf "$f" "$name"
    [ -h "$name" ] || ln -sf "$f" "$name.1"
done
ldconfig