#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" stash
usermod -o -u "$PUID" stash

cat /etc/s6-overlay/s6-rc.d/init-setup/branding

echo '

To support development visit:
https://opencollective.com/stashapp

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u stash)
User GID:    $(id -g stash)
───────────────────────────────────────
"

echo "Applying permissions"
# app
chmod -R "=rwx" "/app"
chown stash:stash "/app"
# config
chmod -R "=rwx" "/config"
chown -Rh stash:stash "/config"
# defaults
chmod "=rwx" "/defaults"
chown stash:stash "/defaults"

function mkown {
  mkdir -p "$1"
  chown -Rh stash:stash "$1"
  chmod -R "=rwx" "$1"
}

echo "Creating Directories"
mkown "/config/plugins"
mkown "/config/scrapers"
mkown "${STASH_GENERATED}"
mkown "${STASH_CACHE}"