#!/usr/bin/with-contenv bash
# shellcheck shell=bash

## check for existing requirements.txt
if [[ ! -f /config/requirements.txt ]]; then
    cp /defaults/requirements.txt /config/requirements.txt
fi

## install and upgrade python requirements
echo "Installing/upgrading python requirements..."
pip3 install --upgrade -q --exists-action i --target "$PIP_INSTALL_TARGET" -r /config/requirements.txt
export PYTHONPATH="$PYTHONPATH:$PIP_INSTALL_TARGET"