#!/command/with-contenv bash
# shellcheck shell=bash

# link download libraries
if [[ ! -e "$/config/.stash/ffmpeg" ]]; then
    ln -s "/usr/local/bin" "/config/.stash/ffmpeg"
fi
if [[ ! -e "/config/.stash/ffprobe" ]]; then
    ln -s "/usr/local/bin/ffprobe" "/config/.stash/ffprobe"
fi