#!/command/with-contenv bash
# shellcheck shell=bash

# link download libraries
if [[ ! -e "$/config/.stash/ffmpeg" ]]; then
    ln -s "$(command -v ffmpeg)" "/config/.stash/ffmpeg"
fi
if [[ ! -e "/config/.stash/ffprobe" ]]; then
    ln -s "$(command -v ffprobe)" "/config/.stash/ffprobe"
fi