name: alpha-build
on:
  push:
    branches:
      - alpha
    paths:
      - 'dockerfile/**'
      - 'stash/**'
      - 'VERSION'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        variant: [alpine, hwaccel, hwaccel-alpine]
        upstream: [development]
    uses: ./.github/workflows/docker-build.yml
    with:
      variant: ${{ matrix.variant }}
      upstream: ${{ matrix.upstream }}
      # develop prefix
      tags: "alpha-${{ matrix.variant }}"
      buildargs: ""
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}