name: clean-images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: Chizkiyahu/delete-untagged-ghcr-action@main
        with:
          owner_type: user
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          except_untagged_multiplatform: true