name: develop-build
on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile/**'
      - 'stash/**'
      - 'VERSION'
  workflow_dispatch:
  repository_dispatch:
    types: [upstream_update]
  schedule:
    - cron: '0 0 */7 * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        variant: [alpine, hwaccel, hwaccel-alpine]
        upstream: [development]
    uses: ./.github/workflows/docker-build.yml
    with:
      variant: ${{ matrix.variant }}
      upstream: ${{ matrix.upstream }}
      # develop prefix
      tags: "${{ matrix.variant }}-develop"
      buildargs: ""
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}